### ISSUE TITLE
SimpleQuery request to 'SET TIME ZONE' generates an exception

### ISSUE THREAD

**Issue by Jerry-Carter** [vapor/postgres-nio#115]
try conn.simpleQuery("SET TIME ZONE INTERVAL '+5:45' HOUR TO MINUTE").wait()

This line generates a message with identifier 'S' and produces an exception in PostgresSimpleQuery::respond(to:).  Specifically,

    throw PostgresError.protocol("Unexpected message during simple query: \(message)")

**Comment by tanner0101** [comment]
Thanks!
