### ISSUE TITLE
Error in PostgresData.init(int)

### ISSUE THREAD

**Issue by Christian-Seiler** [vapor/postgres-nio#124]
In the `PostgresData+Int.swift` file I get the following errors in the initialisers (Lines 4, 8, 12, 16, and 20):

> Cannot convert value of type 'Int' to expected argument type 'ByteBuffer'
> Extraneous argument label 'integer:' in call

I created a vapor project with `vapor new --fluent` and Postgres

From my Package.swift
> .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
> .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
> .package(url: "https://github.com/vapor/fluent-postgres-driver.git", from: "2.0.0")

Resolved Versions:
- postgres-nio: 1.3.1
- swift-nio: 2.14.0

**Comment by grundoon** [comment]
Hi @Christian-Seiler – Was this project freshly created recently? While your resolved `postgres-nio` version is up to date, that `swift-nio` is about 6 months old.

Please try `swift package update` and see if that brings everything into sync.

**Comment by Christian-Seiler** [comment]
Thanks. I also had to delete the contents of the "DerivedData" folder generated by Xcode.
