### ISSUE TITLE
Constraint violations break prepared queries

### ISSUE THREAD

**Issue by Jerry-Carter** [vapor/postgres-nio#128]
In PostgresDatabase+PreparedQuery.swift, in the function respond(to:), the 'E' message is not handled.

This may possibly be as simple as adding:

case .error:
  return []

**Comment by fabianfett** [comment]
This code path is not hit anymore. Do we want to close this @0xTim?

**Comment by 0xTim** [comment]
Yep! @Jerry-Carter feel free to reopen if you're still having issues!
