### ISSUE TITLE
UUID decoding fails

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/postgres-nio#129]
UUID is failing during decode. In code similar to this:

```swift
struct MyObject: Content {
   let id: UUID
}
```

```swift
database.simpleQuery("SELECT id from MyTable").all(decoding: MyObject.self)
```

In MyTable `id` is declared this way:
```sql
id uuid NOT NULL
```

If id is String decode is successful 
```swift
struct MyObject: Content {
   let id: String
}
```

It is failing in `PostgresData.uuid`. Not familiar with `formatCode`. But in case if it is text why we can't use `string` property of `PostgresData` to convert it to UUID?
<img width="794" alt="Screenshot 2020-10-11 at 00 29 42" src="https://user-images.githubusercontent.com/800044/95666335-e14ed680-0b58-11eb-86e1-4bc81015bffd.png">

**Comment by 0xTim** [comment]
@Igor-Palaguta that looks like it's saved as a string in the database, not `.uuid`? Hence why it's falling into the `text` case. Is that correct?

**Comment by Igor-Palaguta** [comment]
@0xTim thanks for reply

Just checked in all tables I have uuid type for identifiers. Not sure, but I think this issue gone when I replaced `simpleQuery(string)` with `query(query, binds)`

**Comment by 0xTim** [comment]
Hmm interesting. I'll close the issue then, feel free to reopen if it continues to be a problem!
