### ISSUE TITLE
Assertion error when fetching a row from PostgreSQL DB that has a field that is over 16 MiB

### ISSUE THREAD

**Issue by axtonpitt** [vapor/postgres-nio#148]
### Describe the bug

Assertion error when fetching a row from PostgreSQL DB that has a field that is over 16 MiB. In my case I had a bytea field of 36.1MB.

### To Reproduce

1. Insert a row into a table with a large sized field (over 16MB). 
2. Fetch this row by ID.
3. Should see `Assertion failed: file NIO/ByteBuffer-core.swift, line 357`

### Expected behavior

Object returned to Vapor application from query.

### Environment

* Vapor Framework version: 4.41.4
* Vapor Toolbox version: 18.3.0
* Fluent version: 4.2.0
* Fluent postgres driver version: 2.1.2
* Postgres kit version: 2.3.0
* Postgres nio version: 1.5.1
* OS version: macOS Big Sur 11.2.1 (20D74)

### Additional context
Screenshot from a part of the call stack:
<img width="931" alt="Screen_Shot_2021-03-13_at_11 56 48_PM" src="https://user-images.githubusercontent.com/8604082/111051304-f38dc180-84b6-11eb-8871-b7fd7f8cfa79.png">

**Comment by fabianfett** [comment]
@axtonpitt Sorry for taking so long to get back to you.

I tried to reproduce this, with this test:

```swift

    func testVeryLargeColumnValue() {
        var conn: PostgresConnection?
        XCTAssertNoThrow(conn = try PostgresConnection.test(on: eventLoop).wait())
        defer { XCTAssertNoThrow( try conn?.close().wait() ) }

        XCTAssertNoThrow(_ = try conn?.simpleQuery("DROP TABLE IF EXISTS \"table_large_column\"").wait())
        XCTAssertNoThrow(_ = try conn?.simpleQuery("""
        CREATE TABLE table_large_column (
            "id" int8 NOT NULL,
            "bytes" bytea,
            PRIMARY KEY ("id")
        );
        """).wait())
        defer { XCTAssertNoThrow(_ = try conn?.simpleQuery(#"DROP TABLE "table_large_column""#).wait()) }
        
        let size = 1024 * 1024 * 32 // 32MiB
        let thirtyTwoMB = [UInt8](repeating: 1, count: size)
        XCTAssertNoThrow(_ = try conn?.query(#"INSERT INTO table_large_column ("id", "bytes") VALUES ($1, $2);"#, [
                                                .init(int64: 1), .init(bytes: thirtyTwoMB)]).wait())
        
        var rows: [PostgresRow]?
        XCTAssertNoThrow(rows = try conn?.simpleQuery(#"SELECT "id", "bytes" FROM "table_large_column";"#).wait())
        XCTAssertEqual(rows?.count, 1)
        XCTAssertEqual(rows?.first?.column("id")?.int, 1)
        XCTAssertEqual(rows?.first?.column("bytes")?.bytes?.count, size)
    }
```

Apparently this works fine for me... Do you maybe have more information that could help me reproduce this issue?

**Comment by fabianfett** [comment]
Would you mind finding out which SwiftNIO version you are running?

**Comment by fabianfett** [comment]
We could eventually reproduce the issue. It is a bug in SwiftNIO, that is fixed now. https://github.com/apple/swift-nio/pull/1813

**Comment by axtonpitt** [comment]
Sorry I didn't get back to you, thanks for getting to the bottom of it!
