### ISSUE TITLE
Docs link in README is a 404

### ISSUE THREAD

**Issue by richardgroves** [vapor/postgres-nio#163]
### Describe the bug

In the README at https://github.com/vapor/postgres-nio#api-docs the link to the documents is a 404 page.
Link target is https://api.vapor.codes/postgres-nio/master/PostgresNIO/

### To Reproduce

Clink the link for the documents

### Expected behavior

The link goes to a work document page

### Environment

* OS version:
Chrome on macOS 15.3

### Additional context
N/A

**Comment by 0xTim** [comment]
Thanks for spotting! This is now fixed
