### ISSUE TITLE
Support for AWS Redshift database

### ISSUE THREAD

**Issue by grennis** [vapor/postgres-nio#166]
**Is your feature request related to a problem? Please describe.**
When attempting to query an AWS Redshift database, I can connect successfully but any query results in the error:

In driver version 1.4.2:
`Uncaught error: NIOPostgres error: protocol error: Unexpected query metadata: SELECT (PostgresNIO/Connection/PostgresConnection+Connect.swift:51)`

In driver version 1.5.2:
`PostgresNIO/PostgresConnection+Database.swift:32: Fatal error: Unexpectedly found nil while unwrapping an Optional value` where it is trying to initialize a `PostgresQueryMetadata` using commandTag `SELECT` which it doesn't parse because it seems to be expecting a number here like `SELECT 3` which I think is the row count.

**Describe the solution you'd like**
It would be great if this driver would work with Redshift which is a postgres variant.

**Describe alternatives you've considered**
I have not been able to find any information on this or any other way to connect to Redshift.

**Comment by 0xTim** [comment]
Looking at the [docs](https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html) there seem to be significant differences between the Postgres implementation and Redshift so I'm not surprised it doesn't work. We might be able to look at removing some of the assumptions around the responses and queries but the priority will be pretty low, especially during the async/await transition process. It would make for w good community contribution though!

You could try connecting using [Soto](https://soto.codes/reference/Redshift.html) either directly or using the data API in the meantime

**Comment by fabianfett** [comment]
Well, I assume that Soto is more about Redshift node and cluster management and not actually running request on Redshift. Looking at the docu, the main differences seem to be around commands that are send on the postgres connection. However in PostgresNIO we don't really care about the supported SQL commands. We just provide the binary formats to execute commands, but we don't do any validation. I'd be eager to know what what the Redshift database returns in metadata, because for the metadata to fail, the request must have been processed correctly before. 

@grennis could you provide the string that is passed to `PostgresQueryMetadata` in `PostgresConnection+Database.swift:32`?

**Comment by fabianfett** [comment]
Urgh. Stupid me @grennis already wrote that only `SELECT` is returned. Looking at the postgres documentation, this looks like Redshift is not conforming to the wire spec at this.

> For a SELECT or CREATE TABLE AS command, the tag is `SELECT rows` where *rows* is the number of rows retrieved

https://www.postgresql.org/docs/13/protocol-message-formats.html See CommandComplete -> String. I guess we could add a fallback to zero with a note that this is for Redshift support. @grennis would you like to provide a pr for this?

**Comment by grennis** [comment]
> Urgh. Stupid me @grennis already wrote that only `SELECT` is returned. Looking at the postgres documentation, this looks like Redshift is not conforming to the wire spec at this.
> 
> > For a SELECT or CREATE TABLE AS command, the tag is `SELECT rows` where _rows_ is the number of rows retrieved
> 
> https://www.postgresql.org/docs/13/protocol-message-formats.html See CommandComplete -> String. I guess we could add a fallback to zero with a note that this is for Redshift support. @grennis would you like to provide a pr for this?

Sure thing. I will try that and see if that's the only issue or if there are more complications, and go from there. Thanks for the fast response!
