### ISSUE TITLE
Passing connection options for database

### ISSUE THREAD

**Issue by jefflewis** [vapor/postgres-nio#320]
**Is your feature request related to a problem? Please describe.**
There is not a current way to specify additional query params for the database connection (e.g. `options=--cluster%3some-app-123`) for servers that might require that (as cockroach DB does for shared database clusters)

**Describe the solution you'd like**
One of the configuration and connection parameters should be an options hash that allows for various string key/values to be applied as an `options` value for the query params.

**Describe alternatives you've considered**
This is a base connection level feature. Being able to pass the options is supported in other database adapters (e.g. ruby's `sequel` gem: https://github.com/jeremyevans/sequel/blob/41d2adf7d89d73fb895cb7eae174b9dc1cec4c7e/lib/sequel/database/connecting.rb#L38) 

**Additional context**
I was attempting to use Vapor/fluent to connect to a cockroachdb cluster to test it out and discovered this issue

**Comment by fabianfett** [comment]
We will need to add this to `PostgresFrontendMessage.Startup` and pipe the additional options `[(String, String)]` through.

**Comment by fabianfett** [comment]
@jefflewis Can you please check if #361 fixes your needs?

**Comment by jefflewis** [comment]
Awesome!

**Comment by fabianfett** [comment]
@jefflewis gentle ping.
