### ISSUE TITLE
cutesy name

### ISSUE THREAD

**Issue by tanner0101** [vapor/postgres-nio#37]
`PostgresNIO` is a bit overly generic and could conflict with new modules in the future. Given Swift and SwiftPM's poor support for dealing with conflicting module name, we might want to consider giving it a less generic, aka "cutesy", name. Any ideas?

**Comment by tanner0101** [comment]
Maybe something to do with elephants?
- loxodant
- elephas
- probos
- ivory 
- phantos

**Comment by Mordil** [comment]
Horton, as in "Horton Hears a Who?"

**Comment by tanner0101** [comment]
- slonik (name of psql elephant)
from Rodil

**Comment by enquora** [comment]
Excellent idea. Nothing communicates the sobriety, maturity and attention to detail wanted in a mission-critical piece of software like a cute meme with a short shelf life. This is certain to attract collaboration from grown-ups with the experience and focus on correctness wanted in a db codebase.
