### ISSUE TITLE
Composable PostgresQuery

### ISSUE THREAD

**Issue by MahdiBM** [vapor/postgres-nio#415]
**Is your feature request related to a problem? Please describe.**
Writing flexible `PostgresQuery`s is very hard.

Imagine there is a raw-sql no-binds query like so:
```swift
let myValue: Int? = nil
let condition = if let myValue {
    "where my_column = '\(myValue)'"
} else {
    ""
}
let query = """
SELECT * FROM my_table \(condition)
"""
```
I can't find a proper way to write this with `PostgresQuery`s.

**Describe the solution you'd like**
Interpolating a `PostgresQuery` into another `PostgresQuery` should work:
```swift
let myValue: Int? = nil
let condition: PostgresQuery = if let myValue {
    "where my_column = \(myValue)"
} else {
    ""
}
let query: PostgresQuery = """
SELECT * FROM my_table \(condition)
"""
```

**Describe alternatives you've considered**

**Additional context**
I can try to implement this myself but i wanted to discuss it first.
I realize it won't be too easy, considering how the underlying sql string works, but not sure what else i'm supposed to do to have such flexibility.
Am i doing it wrong?

**Comment by gwynne** [comment]
```swift
var query: PostgresQuery = """
SELECT * FROM my_table \(unescaped: condition.sql)
"""
```

**Comment by MahdiBM** [comment]
@gwynne that doesn't work though. The underlying PostgresQuery also contains the actual binds. The SQL query also contains numbered `$`s (e.g. `$1`).

**Comment by fabianfett** [comment]
> Writing flexible `PostgresQuery`s is very hard.

In my opinion you should not do this! Chances of screwing up are quite high! 

I haven't written this up, but most adopters should have all their query permutations as individual `PostgresPreparedStatement`s. This means each query permutation gets its own type.

**Comment by fabianfett** [comment]
If this isn't enough flexibility use a framework that provides a SQL building DSL. I have heard people like to use SQLKit for this. ;)
