### ISSUE TITLE
Get count of active connection

### ISSUE THREAD

**Issue by gulivero1773** [vapor/postgres-nio#469]
Need add method for get active connection of database. I do library for health check and I need to get count active connection from psql. I send sql request - SELECT * FROM pg_stat_activity WHERE datname = 'dbname' and state = 'active'; and I have this struct in response - PostgresRandomAccessRow, but I don't have permission for get lookupTable and get count of active connections

**Comment by MahdiBM** [comment]
I'm pretty sure the current API is sufficient, but not 100% sure of the function names.

I think you shouldn't even use `PostgresRandomAccessRow` row when possible. Just use `PostgresRow` and [decode the rows into a tuple](https://api.vapor.codes/postgresnio/documentation/postgresnio/postgresrow/decode(_:context:file:line:)-78rj9):
```swift
let (field1, field2) = myPostresRow.decode((String, Int).self, context: .default)
```
Make sure the tuple covers all rows that are returned, and in order. I'd suggest not using `*` and specifying the fields.

You could still use [`PostgresRandomAccessRow` and its subscripts](https://api.vapor.codes/postgresnio/documentation/postgresnio/postgresrandomaccessrow), but using `PostgresRow` like i mentioned is the best / most-performant way.

**Comment by MahdiBM** [comment]
Feel free to let me know if i'm wrong or you'll need some more functions marked as API (and for what reasons).

**Comment by gulivero1773** [comment]
<img width="1274" alt="Знімок екрана 2024-04-24 о 15 20 51" src="https://github.com/vapor/postgres-nio/assets/61082418/999e5221-4985-43a1-975b-85d8e79b6167">
@MahdiBM When I use this code I have fatal error

**Comment by gulivero1773** [comment]
`            let rows = try await (app.db(.psql) as? PostgresDatabase)?.simpleQuery("SELECT * FROM pg_stat_activity WHERE datname = 'test' and state = 'active';").get()
            let row = rows?.first?.makeRandomAccess()
            rows?.forEach { rowNew in
                let res = try? rowNew.decode((String, Int).self, context: .default)

            }`
