### ISSUE TITLE
please don't use anything *unsafe*

### ISSUE THREAD

**Issue by weissi** [vapor/postgres-nio#47]
Code that contains the word `*unsafe*` is just as unsafe as C(++) code. In Swift there shouldn't be a necessity to use unsafe code unless we're interfacing with C(++).

Please file a NIO bug if there's anything that's not C(++) interop that you can't express without `*unsafe*`. See #46 , #45 , #44 for what happens with `*unsafe*` APIs.

**Comment by tanner0101** [comment]
The only thing left in this package with `unsafe` is the `getUUID` method's usage of `Swift.withUnsafeMutableBytes(of:)`. 👍

**Comment by weissi** [comment]
Thank you @tanner0101 for looking into this so quickly
