### ISSUE TITLE
PostgresClient should support `additionalStartupParameters`

### ISSUE THREAD

**Issue by thoven87** [vapor/postgres-nio#518]
**Is your feature request related to a problem? Please describe.**
Allow options to set the Application names for each connection/Query

**Describe the solution you'd like**
PostgresClient.Configuration should accept application name

It makes debuting which application querying the database for debug/audit purposes

Active queries can be retrieves easily with 

```SQL
SELECT 
    pid
    datname,
    usename,
    application_name,
    client_hostname,
    client_port,
    backend_start,
    query_start,
    query,
    state
FROM pg_stat_activity
WHERE state = 'active';
```

**Describe alternatives you've considered**
Alternatively, a connection string should be allow to set the application instead of calling 
`postgresql://username@localhost/database?application_name=my_application`
```swift
withConnection{ connection in
 connection.query("SET application_name TO my_application")
let stream = connection.query("Some query")
}
`

**Additional context**
This is very useful incases where multiple services can access the same database.

**Comment by gwynne** [comment]
@fabianfett Looks like this is available through the old `PostgresConnection` configuration but not through `PostgresClient`'s.

**Comment by fabianfett** [comment]
@thoven87 sorry for the very slow response. You can achieve this with todays `PostgresConnection` API:

```
var configuration = PostgresConnection.Configuration(username: "my_username", tls: .disable)
configuration.options.additionalStartupParameters = [("application_name", "my_application")]
```

As @gwynne points out, this is not possible with today's PostgresClient API. However it should be fairly trivial to add this behavior.

**Comment by thoven87** [comment]
> @thoven87 PR raised as #521.

Thank you! I'll take a look soon!
