### ISSUE TITLE
Invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by adtrevor** [vapor/postgres-nio#52]
Fluent attempts to save strings that contains the NULL character, it seems to be linked to JSON serialised values as this repo demonstrates:
https://github.com/adtrevor/FluentPosgresNullCharBug

The resulting error is:
```
ERROR:  22021: invalid byte sequence for encoding "UTF8": 0x00
LOCATION:  report_invalid_encoding, wchar.c:2017
```

Thank you

**Comment by tanner0101** [comment]
Where does the null character (0x00) appear in the JSON?

If it's appearing in a value string, that's not valid according to spec. Null characters should be represented as `\u0000`. 

```json
{"string": "foo\u0000bar"}
```

See the spec for value here:

```
      string = quotation-mark *char quotation-mark

      char = unescaped /
          escape (
              %x22 /          ; "    quotation mark  U+0022
              %x5C /          ; \    reverse solidus U+005C
              %x2F /          ; /    solidus         U+002F
              %x62 /          ; b    backspace       U+0008
              %x66 /          ; f    form feed       U+000C
              %x6E /          ; n    line feed       U+000A
              %x72 /          ; r    carriage return U+000D
              %x74 /          ; t    tab             U+0009
              %x75 4HEXDIG )  ; uXXXX                U+XXXX

      escape = %x5C              ; \

      quotation-mark = %x22      ; "

      unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
```

**Comment by tanner0101** [comment]
It turns out the problem was attempting to submit `TIMESTAMPTZ` formatted data to a query expecting `JSON` formatted data. A failure here is expected. 

However, this does bring up a possible enhancement to postgres nio:
https://github.com/vapor/postgres-nio/issues/53
