### ISSUE TITLE
Calling postgresql function appears to fail

### ISSUE THREAD

**Issue by duncangroenewald** [vapor/postgres-nio#523]
### Describe the issue

When calling a postgresql function the query fails saying the function cannot be found - this appears to be related to that way the function parameters are being passed.

### Vapor version

N/A - using only postgres-nio

### Operating system and version

macOS 15.1.1

### Swift version

5.10.0

### Steps to reproduce

Create a function and call it using Postgres-nio apis

`        let rows = try await client.query("select get_all_fixture_changes(\(launchPeriod.startDate), \(launchPeriod.endDate), \(prevLaunchPeriod.startDate), \(prevLaunchPeriod.endDate));")
`

### Outcome

The following error is returned 

Error creating report PSQLError(code: server, serverInfo: [sqlState: 42883, file: parse_func.c, hint: No function matches the given name and argument types. You might need to add explicit type casts., line: 636, message: function get_all_fixture_changes(timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone) does not exist, position: 8, routine: ParseFuncOrColumn, localizedSeverity: ERROR, severity: ERROR], triggeredFromRequestInFile: XXXX/XXXX+XXXX.swift, line: 97, query: PostgresQuery(sql: select get_all_fixture_changes($1, $2, $3, $4);, binds: [(****; TIMESTAMPTZ; format: binary), (****; TIMESTAMPTZ; format: binary), (****; TIMESTAMPTZ; format: binary), (****; TIMESTAMPTZ; format: binary)]))

### Additional notes

The function works fine when run from pgAdmin SQL screen and is defined as follows:

```
create or replace function makespace.get_all_fixture_changes(csd timestamptz, 
ced timestamptz, psd timestamptz, ped timestamptz)
```

Any idea if calling functions like this is supported from Postgres-nio ?

**Comment by gwynne** [comment]
This is absolutely supported by PostgresNIO. At the risk of missing something obvious, it looks like your problem might be that your function is not in the `public` schema and the schema it _is_ in is not in the current `search_path`. Does it work if you write the query as `select makespace.get_all_fixture_changes(...)`?

**Comment by duncangroenewald** [comment]
Glad to hear that, that was my first thought but it doesn't work when using ` select makespace.get_all_fixture_changes(...)` either.

**Comment by gwynne** [comment]
Not that I'm aware of. I'm afraid I don't know what's up here; @fabianfett might have an idea.

**Comment by duncangroenewald** [comment]
Definitely a little strange because I have other functions that are embedded in prepared statements and I have to cast the TIMESTAMPTZ parameter to a DATE otherwise I get a similar error saying the function is not found.  

For the function above casting parameters to DATE doesn't fix the problem, I still get the 'function not found error' - not withstanding the fact that casting the Swift Date, which has time zone, to postgresql DATE, which doesn't, is going to probably result in an error when used in a comparison.

**Comment by duncangroenewald** [comment]
OK - my bad - test was against a different version of the database with an old version of the function !!

**Comment by duncangroenewald** [comment]
OK I am re-opening this issue because it's unclear how I fetch the data returned from this function.

Is there a Swift code example of how one calls such a function and processes the returned rows ?

**Comment by duncangroenewald** [comment]
@gwynne - is there a source code example of calling a Postgres function and processing the results.  The usual manner does not appear to work - it doesn't seem like the function is returning the usual Postgres row.

What am I missing here ?


Error creating report PostgresDecodingError(code: typeMismatch, columnName: \"get_all_fixture_changes\", columnIndex: 0, targetType: Swift.String, postgresType: RECORD, postgresFormat: binary, postgresData: ByteBuffer { readerIndex: 0, writerIndex: 105, readableBytes: 105, capacity: 105, storageCapacity: 8192, slice: _ByteBufferSlice { 93..<198 }, storage: 0x0000000123016e00 (8192 bytes) }\nreadable bytes (max 1k): [ 00 00 00 07 00....

**Comment by duncangroenewald** [comment]
OK well this is obtuse !!


it seems one needs to call the function like so in order to get the data returned in the usual fashion !

` let rows = try await client.query("select * from makespace.get_all_fixture_changes(\(launchPeriod.startDate), \(launchPeriod.endDate), \(prevLaunchPeriod.startDate), \(prevLaunchPeriod.endDate));")`

**Comment by duncangroenewald** [comment]
Solved

**Comment by gwynne** [comment]
It depends on what type the function returns. If it returns a record or row type, then yes you would need to do it like that. If it returns an array or scalar type, you could do it with an `AS` alias.

**Comment by gwynne** [comment]
I was referring to this syntax for renaming result columns:
```sql
select makespace. makespace.get_all_fixture_changes(...) as changes;
```
