### ISSUE TITLE
Add a getter for the `PostgresClient` for `eventLoop: EventLoop`

### ISSUE THREAD

**Issue by zamderax** [vapor/postgres-nio#528]
### Please summarize your feature request

Need the eventLoop

### Describe the functionality you're seeking in more detail

When constructing a `postgresClient: PostgresClient` like below we can pass in an `eventLoopGroup` option. 

```swift
let pgClient: PostgresClient = PostgresClient(
  configuration: .init(
      host: pgHost,
      port: pgPort,
      username: pgUser,
      password: pgPassword,
      database: pgDatabase,
      tls: .disable
  ),
  eventLoopGroup: eventLoopGroup,
  backgroundLogger: logger
)
```

However, when passing the `pgClient` variable around in later parts of an application, we can't seem to get the `eventLoop` or `eventLoopGroup` variable. 

Can we add a public get property called 

`pgClient.eventLoopGroup`?

**Comment by gwynne** [comment]
`PostgresClient` is built around a Concurrency-based API, its need for an `EventLoopGroup` is essentially just an implementation artifact - it's usually recommended that you let it use the default group. Why do you need to get the ELG back out of it?

**Comment by zamderax** [comment]
I was trying to create a custom PostgresNIO Casbin adapter similar to whats done here however this example is using Fluent: 
https://github.com/SwiftCasbin/fluent-adapter/blob/master/Sources/CasbinFluentAdapter/CasbinFluentAdapter.swift

It looks like the library requires the database.eventLoop so I figured that I would need the same.

**Comment by gwynne** [comment]
Fluent databases do need an event loop, yes, and that library is old enough to be based on futures rather than Concurrency, which is why it needs it. But `PostgresClient` doesn't use futures, so you don't need an event loop in order to work with it.
