### ISSUE TITLE
lazy data serialization

### ISSUE THREAD

**Issue by tanner0101** [vapor/postgres-nio#53]
Currently `PostgresData` values are serialized to the expected data format upon initialization. For example:

```swift
import Foundation
import PostgresNIO

let date = PostgresData(date: Date())
```

Upon initialization, `date` contains `TIMESTAMPTZ` formatted bytes ready for querying. The `Date` supplied is discarded.

While this approach is simple, it has a draw back. Take the following query:

```sql
SELECT $1::JSON as "date"
```

If we attempted to pass the `date` data from above to this query, we would get a warning followed by an error:

```
2019-10-18T15:12:42-0400 warning: bind $1 type (TIMESTAMPTZ) does not match expected parameter type (JSON)
2019-10-18T15:12:42-0400 error: invalid byte sequence for encoding "UTF8": 0x00 (report_invalid_encoding)
```

It makes sense that `TIMESTAMPTZ` should not be convertible to `JSON`, however, the original `Date` object we had earlier _does_ know how to convert to JSON. It can do so via `Codable` and the `JSONEncoder`.

If `PostgresData` could support lazy serialization of Swift types, then we could support passing a `Date` to this query dynamically.

**Comment by tanner0101** [comment]
Although #63 did a lot to help this issue, lazy data serialization could still have some benefits. Postgres is able to convert between _most_ types itself, but there are some that it can't. For example: `JSON[]` to `JSONB`. This can be an issue if you store a property like `users: [User]` on your model and set the table's data type to `JSONB` or `JSON[]`. PostgresData must determine when it gets `[User]` whether to convert it to `JSONB` or `JSON[]` immediately. Depending on which decision is made, the resulting data may be incompatible with the column's expected data type.

If data could serialize lazily, then `[User]` could theoretically know how to serialize to both `JSONB` and `JSON[]`. The Swift array would be passed through the query chain until the desired data type has been resolved and the array can be asked to serialize.

The one major caveat here as discovered in #63 is that this will require an extra round trip for each query since the client must wait until the DB returns its desired parameter types before sending the bind command.

**Comment by fabianfett** [comment]
@gwynne I think this is something we should not support... WDYT?

**Comment by fabianfett** [comment]
I do think this is a non goal right now. Let's close this for now.
