### ISSUE TITLE
returns only one character from char(3) field

### ISSUE THREAD

**Issue by Maxim-Inv** [vapor/postgres-nio#79]
I have a table with a field of char(3) type. When I execute a query I got only one symbol instead all three characters. The data is ok in database, I see all three characters.

https://github.com/vapor/postgres-nio/blob/master/Sources/PostgresNIO/Data/PostgresData%2BString.swift#L50

For example, currency.column("id") - `"id": 0x594552 (BPCHAR)`.

**Comment by Maxim-Inv** [comment]
The workaround is use varchar(3) instead char(3)

**Comment by Maxim-Inv** [comment]
it relates to #71

**Comment by tanner0101** [comment]
Thanks for reporting @Maxim-Inv
