### ISSUE TITLE
Should a terminate message be sent to the server on connection close()?

### ISSUE THREAD

**Issue by sqlisor** [vapor/postgres-nio#84]
Switching from libpq to postgres-nio, some of my unit tests failed because connections were still alive on the server after closing them on the client.
The connections only disappeared after closing the application.
This can be seen in `pg_stat_activity`
Sending a terminate message to the server in close() fixed the problem 
```    
public func close() -> EventLoopFuture<Void> {
    guard !self.didClose else {
        return self.eventLoop.makeSucceededFuture(())
    }    
    let _ = self.requestTerminate(logger: logger)
    ...
```

```
extension PostgresMessage {

    public struct Terminate: PostgresMessageType {
        
        public static var identifier: PostgresMessage.Identifier {
            return .terminate
        }
        
        public var description: String {
            return "Terminate"
        }
        
        public func serialize(into buffer: inout ByteBuffer) {
        }
    }
}
```

Is this a bug?

**Comment by tanner0101** [comment]
@sqlisor yeah this seems like a bug to me. MySQLNIO sends a close message to the server before closing so we should follow suit here if that's also what Postgres wants.
